### ISSUE TITLE
Alarm is not triggerd: mobile number format

### ISSUE THREAD

**Issue by Scyten** [0x5ECF4ULT/PanicTrigger#31]
Hi,
I have tried your App!
But I was not able to trigger the alarm.
1th Mobile: I didn't change the trigger word and entered my the Destination mobile number.
2nd Mobile: Unchanged triggerword. I entered the nr. from 1th: With no white Spacey and with Out the international prefix. Is that the right format?

The SMS goes out and is recieved. But no alarm is triggered. I think the problem is the format of the mobile number.

Any advice? Testet on Pixel 3XL Android 10 and Galaxy S4 with Android 7.1.2

**Comment by Scyten** [comment]
Ok, the Nr Format is +<countycode><number without white space>
I know the problem why the alarm is not triggered:
When an SMS arrives in content and the mobile number is checked. 
1. Content check works.
2. But there is a bug in the code that checks the mobile number:
`if (contacts.contains(msg.getOriginatingAddress()) && msgs.contains(msgParts[0]))`
contacts is in such a format: +1XXXXXXXXXX;<Name>;General 
but msg.getOriginatingAddress() returns only the mobile number, therefore the if-clause is always false and no alarm every triggerd.

**Comment by 0x5ECF4ULT** [comment]
Hello.
Thanks for your issue and PR #32. Unfortunately this project is currently unmaintained and will face a complete rewrite. Sadly I have to close your PR for now but I'm really grateful for it. If you are still interested at the time the rewrite will happen I'll happily review your upcoming contributions.

**Comment by cauerego** [comment]
any estimated time of when will the project be rewritten? 

given the sparse dates among the messages above, i would assume it's still abandoned. 😒

such a simple and wonderful idea, i'm willing to try and pick it up if you're going to keep it unmaintained. 😏
